"""Adicionar itens no pedido

Revision ID: a0c81e3fcf8b
Revises: fd12f1592bde
Create Date: 2025-08-24 16:26:21.396267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c81e3fcf8b'
down_revision: Union[str, Sequence[str], None] = 'fd12f1592bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
